name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
env:
  PYTHON_VERSION: '3.10'

jobs:
  lint-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Using Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Lint Job
      run: |
        cd backend
        pipenv run flake8 .
  
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Using Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Test Job
      run: |
        cd backend
        pipenv run pytest

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Using Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Pipenv
      run: |
        cd backend
        pip install pipenv

    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev

    - name: Build, Run Jobs
      run: |
        cd backend
        docker build --tag backend-movie-picture:latest .
        docker run -p 5000:5000 --name backend-movie-picture -d backend-movie-picture